### PR TITLE
fix scroll and navbar on landscape

### LINKED ISSUE #421: Improper height on mobile, needs adjustment (iPhone X)
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in QA
    * Followed all applicable steps in the TROUBLESHOOTING guide: TODO
    * Checked for relevant discussions on Discord: <https://discord.gg/pPERUuv>
    * Checked that your issue isn't already filed: <https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues>

### Description

When testing the application on mobile, I've noticed that the height of our application is misaligned, and certain elements are unreachable

RPReplay_Final1586230866

ezgif com-video-to-gif (2)

### Steps to Reproduce

1. Visit app on mobile http://coronatrackerv1.s3-website-us-east-1.amazonaws.com/
2. Try scrolling down on health log, about page

**Expected behavior:**

All elements are visible to the user and reachable (at least by scrolling)

**Actual behavior:**

Certain elements are cut off and unreachable

**Reproduces how often:**

100%

### Versions

0.3.2

### PR DESCRIPTION
**Pull request by AdhamAH**
## IMPORTANT: Please do not create a Pull Request without creating an issue first.

**Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request.**

**Do not change the following line aside from replacing YOUR-ISSUE-HERE with the issue this PR fixes** 

fixes #421 and also fixes the NavBar on the landscape view on some devices and any problem related to the NavBar position 

### Test plan (required)

Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

scroll

### Final Checklist

- [x] Have you bumped the version in `package.json`?
    - Second decimal for major change, third decimal for minor change. This can go past 10 i.e. 1.0.9 !=> 1.1.0, 1.0.9 => 1.0.10
    - [Read here for more info](https://semver.org/)
- [ ] Have you added any new tests necessary?
- [x] Is your PR rebased off the most current master?
- [x] Have you squashed all commits, or if you will merge will you squash all commits?
- [x] Did you use yarn, not npm?
- [x] Did you use Material-UI wherever possible?
- [x] Did you format according to Prettier?
- [x] Did you run all of your most recent changes locally to make sure everything is working?

### CODE REVIEW

File: client/src/components/Layout.jsx [hunk 1]
```diff
@@ -23,14 +23,21 @@ const theme = createMuiTheme({
...
   },
+  
 });
 const useStyles = makeStyles(() => ({
   root: {
     textAlign: 'center',
     backgroundImage: 'linear-gradient(#d7e1fa, #bbcef9)',
-    overflowY: 'auto',
-    height: '85vh',
+    overflowY: 'scroll',
```
Comment (acthelemann) [inline client/src/components/Layout.jsx:32]: On a Windows desktop, `scroll` will leave a permanent scroll bar on the screen while `auto` will add the scroll bar only if necessary.

I recommend always using `auto` over `scroll`.

Comment (SomeMoosery) [reply client/src/components/Layout.jsx:32]: I may not be good practice but since I have a PR out I just added this change to [mine](https://github.com/COVID-19-electronic-health-system/Corona-tracker/pull/425).
