### PR TITLE
Fixed routing to Education 

### LINKED ISSUE #196: Education tab not rendering component
* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in QA
    * Followed all applicable steps in the TROUBLESHOOTING guide: TODO
    * Checked for relevant discussions on Discord: <https://discord.gg/pPERUuv>
    * Checked that your issue isn't already filed: <https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues>

### Description

When running the app in QA, navigating to the Education tab does not render anything. This looks to be a problem in the render parameter in the associated `PrivateRoute`.

### Steps to Reproduce

1. Run the application in QA
2. Navigate to education tab

**Expected behavior:**

Education tab loads flashcards as it was before

**Actual behavior:**

Nothing renders

**Reproduces how often:**

100%

### PR DESCRIPTION
**Pull request by awu556**
Changed attribute in PrivateRoute (render => component). You can now navigate to the education page. Also added state to the Disclaimer.js so when uncommented, the disclaimer will disappear after agreeing. 

fixes #196

### CODE REVIEW

File: client/src/components/Disclaimer.js [hunk 1]
```diff
@@ -4,25 +4,32 @@ import { ReactComponent as TextLogo } from '../img/Logo_CORONATRACKER_Text_Logo.
...
+            <div>
+              <Button className="theme-Palette-white-text" onClick={() => setModalHidden(false)}>
+                I agree
+              </Button>
+              <Button className="theme-Palette-white-text theme-Palette-red-bg">I don't agree</Button>
+            </div>
+          </div>
         </div>
-      </div>
+      ) : null}
```
Comment (SomeMoosery) [inline client/src/components/Disclaimer.js]: While this will be needed in the future, we should try to keep PRs scoped to tackling one issue at a time.

We should remove this but then should definitely open up another issue addressing making `Disclimaer.js` stateful, and when we do, we'll want to use Redux as we should try and keep it as much of a SSOT as possible!

Comment (awu556) [reply client/src/components/Disclaimer.js]: Good point, I'll remove it for now and just add the fix for the route!

Comment (AdhamAH) [reply client/src/components/Disclaimer.js]: I was typing haha! but @SomeMoosery. Also I wanted to point out that there is an issue [here](https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues/188) and soon will be changed to material-ui
