### PR TITLE
Weekly slider bug fix

### LINKED ISSUE #640: [BUG] Swiping on WeeklyTrackerDay does nothing
# ⚠️ IMPORTANT: Please fill out this template to give us as much information as possible to address the issue.

### Prerequisites

- [x] check this box if you have completed the following:
    - Reproduced the problem in QA
    - Reviewed the [contributing guidelines](https://github.com/COVID-19-electronic-health-system/.github/blob/master/CONTRIBUTING.md) and [support](https://github.com/COVID-19-electronic-health-system/.github/blob/master/SUPPORT.md) files
    - Reviewed the README file for the repository you are working in
    - Searched for relevant instructions [on our Discord server](https://discord.gg/pPERUuv)
    - Searched the issues of the repository you are working in to make sure one was not already filed

### Description of the Bug/Issue

Title is self-explanatory, swiping on a WeeklyTrackerDay card doesn't open the "Show me More" page

### Steps to Reproduce

1. Log in
2. Swipe on a WeeklyTrackerDay card

### Expected Behavior

Opens "Show Me More" page

### Actual Behavior

Nothing happens

### Reproduces How Often

100%

### PR DESCRIPTION
**Pull request by PhurbaSherpa**
# ⚠️ __IMPORTANT: Please do not create a Pull Request without creating an issue first.__

All changes need to be discusssed before proceeding. Failure to do so may result in the pull request being rejected.

Please be sure to review our [Code of Conduct](https://github.com/COVID-19-electronic-health-system/.github/blob/master/CODE_OF_CONDUCT.md), [Contributing Guidelines](https://github.com/COVID-19-electronic-health-system/.github/blob/master/CONTRIBUTING.md), and [Support documentation](https://github.com/COVID-19-electronic-health-system/.github/blob/master/SUPPORT.md) before submitting a pull request.

-----

## Please include the issue number the pull request fixes by replacing YOUR-ISSUE-HERE in the text below.

Fixes #640

## Summary

After swiping on weeklyTrackerDay it takes you to showMeMore of the single observation.

## Details

In a previous PR I had fixed how the toggle Value was set so now toggleValue 'showMeMore' should take you to your observations instead of 'myHealthLog'.

I also noticed that SurveyPage1 styling was off from my last PR so I made a small change

## Test Plan (required)

weekly

## Final Checklist

- [x] For CoronaTracker, did you bump the version in `package.json`?
    - Update the second decimal for a major change
    - Update the third decimal for a minor change
    - Numbers can go past 9, e.g. `1.0.9` => `1.0.10`
    - For more info, read about [Semantic Versioning](https://semver.org/)
- [x] Did you add any new tests as necessary?
- [x] Is your PR rebased off the most current master?
- [x] Have you squashed all commits? _(can be done at merge)_
- [x] Did you use `yarn` not `npm`? _(important!)_
- [x] Did you use Material-UI wherever possible?
- [x] Did you run `yarn lint` on the code?
- [x] Did you run all of your most recent changes locally to make sure everything is working?

### CODE REVIEW

File: client/src/components/survey/SurveyPage1.jsx [hunk 1]
```diff
@@ -108,7 +108,7 @@ const SurveyPage1 = props => {
 
   return (
     <div className={classes.root}>
-      <Grid container justify="center" alignItems="center" spacing={4}>
+      <Grid container justify="center" alignItems="center">
```
Comment (acthelemann) [inline client/src/components/survey/SurveyPage1.jsx:111]:
```suggestion
      <Grid container justify="center" alignItems="center" spacing={4}>
```

I see why you're removing the spacing, but I think it looks good if we keep it and handle the [negative margin](https://material-ui.com/components/grid/#negative-margin). Replace `paddingBottom: '10em',` with `
    padding: '16px 16px 10em 16px',` in the `root` class and that should solve this issue.

**Comment by PhurbaSherpa** [comment]
> Awesome! Just realized you graduated from Stony Brook - me too

Yeah I was part of the 2019 class. Go Seawolves!

**Comment by SomeMoosery** [comment]
Will need a bump of `package.json` as something else merged in
