### PR TITLE
error messages added for subscribe/unsubscribe with phone number

### LINKED ISSUE #538: Add message after failed unsubscribe
## Summary

If a user fails to unsubscribe a phone number - the phone number could have not been subscribed in the first place or there could be an internal server error - display a message explaining that it failed.

- [ ] Display message that phone number was not subscribed if service returns a `404` status code
- [ ] Display generic error message for any other failing status code

## Motivation

User should know when their unsubscribe request failed.

### LINKED ISSUE #539: Add message after failed subscribe
## Summary

If a user fails to subscribe a phone number - the phone number could have already been subscribed in the first place or there could be an internal server error - display a message explaining that it failed.

- [ ] Display message that phone number was already subscribed if service returns a `409` status code
- [ ] Display generic error message for any other failing status code

## Motivation

User should know when their subscribe request failed.

### PR DESCRIPTION
**Pull request by luky1300**
## IMPORTANT: Please do not create a Pull Request without creating an issue first.

**Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request.**

**Do not change the following line aside from replacing YOUR-ISSUE-HERE with the issue this PR fixes** 

fixes #538, fixes #539 

### Test plan (required)

Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

### Final Checklist

- [x] Have you bumped the version in `package.json`?
    - Second decimal for major change, third decimal for minor change. This can go past 10 i.e. 1.0.9 !=> 1.1.0, 1.0.9 => 1.0.10
    - [Read here for more info](https://semver.org/)
- [ ] Have you added any new tests necessary?
- [x] Is your PR rebased off the most current master?
- [ ] Have you squashed all commits, or if you will merge will you squash all commits?
- [x] Did you use yarn, not npm?
- [x] Did you use Material-UI wherever possible?
- [x] Did you format according to Prettier?
- [x] Did you run all of your most recent changes locally to make sure everything is working?

corona-err-subscribe

### CODE REVIEW

File: client/src/components/More.jsx [hunk 1]
```diff
@@ -172,7 +218,7 @@ const More = () => {
             <Button
               onClick={() => {
                 subscribe();
-                handleClose();
+                // handleClose();
```
Comment (SomeMoosery) [inline client/src/components/More.jsx:221]: Remove comment

File: client/src/components/More.jsx [hunk 2]
```diff
@@ -182,7 +228,7 @@ const More = () => {
             <Button
               onClick={() => {
                 unsubscribe();
-                handleClose();
+                // handleClose();
```
Comment (SomeMoosery) [inline client/src/components/More.jsx:231]: Remove comment

File: client/src/components/More.jsx [hunk 3]
```diff
@@ -110,7 +136,17 @@ const More = () => {
         );
       })
       .catch(err => {
-        console.log(err);
+        let errorMessage = '';
```
Comment (SomeMoosery) [inline client/src/components/More.jsx:139]: Could we have a higher-level `errorMessage` variable so as to not declare it twice?

File: client/package.json [hunk 4]
```diff
@@ -1,6 +1,6 @@
 {
   "name": "corona-tracker",
-  "version": "1.0.0",
+  "version": "1.0.1",
```
Comment (SomeMoosery) [inline client/package.json:3]: Please rebase off current master
