### PR TITLE
Fix cards postion

### LINKED ISSUE #465: Flashcards need to be better positioned for all screen sizes
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in QA
    * Followed all applicable steps in the TROUBLESHOOTING guide: TODO
    * Checked for relevant discussions on Discord: <https://discord.gg/pPERUuv>
    * Checked that your issue isn't already filed: <https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues>

### Description

Flashcards are displayed too highly, blocking text

Screen Shot 2020-04-10 at 10 23 04 PM

### Steps to Reproduce

1. Log in
2. Go to flashcards

**Expected behavior:**

- [ ] Flashcards are centered in screen and fit between top-level components such as the logo at the top, and bottom nav
- [ ] Text is changed to remove "TODOARROW" and replace with something more fitting

**Actual behavior:**

Flashcards are too high

**Reproduces how often:**

100%

### Versions

0.3.16

### PR DESCRIPTION
**Pull request by AdhamAH**
## IMPORTANT: Please do not create a Pull Request without creating an issue first.

**Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request.**

**Do not change the following line aside from replacing YOUR-ISSUE-HERE with the issue this PR fixes** 

fixes #465 closes #467 

### Test plan (required)

Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

Screenshot 2020-04-13 at 04 12 40

### Final Checklist

- [x] Have you bumped the version in `package.json`?
    - Second decimal for major change, third decimal for minor change. This can go past 10 i.e. 1.0.9 !=> 1.1.0, 1.0.9 => 1.0.10
    - [Read here for more info](https://semver.org/)
- [ ] Have you added any new tests necessary?
- [x] Is your PR rebased off the most current master?
- [ ] Have you squashed all commits, or if you will merge will you squash all commits?
- [x] Did you use yarn, not npm?
- [x] Did you use Material-UI wherever possible?
- [x] Did you format according to Prettier?
- [x] Did you run all of your most recent changes locally to make sure everything is working?

### CODE REVIEW

File: client/src/components/Card.jsx [hunk 1]
```diff
@@ -5,63 +5,91 @@
...
-      <footer style={{ textAlign: 'left' }}>
+    <Grid>
+      <Typography color="secondary" variant="subtitle1">
+        False or True?
+      </Typography>
+      <Typography paragraph variant="body1">
+        {question}
+      </Typography>
+      <footer>
         {footer}
```
Comment (acthelemann) [inline client/src/components/Card.jsx:85]:
```suggestion
        <Typography variant="caption">{footer}</Typography>
```

For consistency

Comment (AdhamAH) [reply client/src/components/Card.jsx]: done! good catch!
