### PR TITLE
Survey bug fixes (#404, #417, #419)

### LINKED ISSUE #404: Sometimes doesn't redirect to homepage on survey submission
# Blocked by #390 

### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in QA
    * Followed all applicable steps in the TROUBLESHOOTING guide: TODO
    * Checked for relevant discussions on Discord: <https://discord.gg/pPERUuv>
    * Checked that your issue isn't already filed: <https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues>

### Description

Sometimes, after finishing the survey, the user is not redirect to the Health Log page.

### Steps to Reproduce

1. Log in 
2. Complete a survey
3. Wait to see if you are redirected

**Expected behavior:**

Redirected to homepage 

**Actual behavior:**

Don't navigate away from survey, or navigate back to page 1 because of Redux update

**Reproduces how often:**

~50%

### Versions

0.2.22

### LINKED ISSUE #417: openComment saves to next survey
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in QA
    * Followed all applicable steps in the TROUBLESHOOTING guide: TODO
    * Checked for relevant discussions on Discord: <https://discord.gg/pPERUuv>
    * Checked that your issue isn't already filed: <https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues>

### Description

Currently, when using the new survey flow, when adding in additional comments, these do not get added to the observations properly. They either
- are only added to the current observation if you click out of the text field before submitting
- are added to the next observation you complete if you don't click out of the text field before submitting 

This is likely due to `SurveyPage3` not updating state between entering text, submitting the third page, and creating an actual observation for Gaia.

### Steps to Reproduce

1. Complete a survey without clicking out of the text field
2. Complete another survey and inspect, seeing the prior survey's openComment as this new survey's openComment 

**Expected behavior:**

The additional comments are attached to the current observation

**Actual behavior:**

The additional comments will sometimes be attached to the wrong survey

**Reproduces how often:**

100%

### Versions

0.3.0

### LINKED ISSUE #419: Cannot scroll on About page on mobile view
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in QA
    * Followed all applicable steps in the TROUBLESHOOTING guide: TODO
    * Checked for relevant discussions on Discord: <https://discord.gg/pPERUuv>
    * Checked that your issue isn't already filed: <https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues>

### Description

On mobile view, we're unable to scroll down on the `About` page. This is likely because the `Layout.jsx` has `overflow: hidden` set. We want to make the `About` page scrollable while ensuring we don't negatively affect other components (i.e. don't just change the `overflow` in `Layout`). This was recently changed to prevent horrible scroll boxes from showing up on certain desktop views.

### Steps to Reproduce

1. Log in 
2. Try scrolling on `About` page

### Versions

0.3.1

### PR DESCRIPTION
**Pull request by acthelemann**
## IMPORTANT: Please do not create a Pull Request without creating an issue first.

**Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request.**

**Do not change the following line aside from replacing YOUR-ISSUE-HERE with the issue this PR fixes** 

fixes #404, fixes #417, fixes #419

### Explain the **details** for making this change. What existing problem does the pull request solve?

**#404**: Survey now redirects to home page on successful submission. @JWaltuch 

**#417**: Comments now save properly on survey submission.

**#419**: Certain pages (Home page, about page, etc.) that could not scroll vertically now can.

### Test plan (required)

Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

**#404**: Submit a survey, make sure the home page is automatically naviagated to.

**#417**: Submit a survey, click on the current date on the calendar, make sure the comment appears in the weekly tracker below the calendar.

**#419**: View the about page on desktop and mobile, make sure it is scrollable.

### Final Checklist

- [x] Have you bumped the version in `package.json`?
    - Second decimal for major change, third decimal for minor change. This can go past 10 i.e. 1.0.9 !=> 1.1.0, 1.0.9 => 1.0.10
    - [Read here for more info](https://semver.org/)
- [x] Have you added any new tests necessary?
- [x] Is your PR rebased off the most current master?
- [x] Have you squashed all commits, or if you will merge will you squash all commits?
- [x] Did you use yarn, not npm?
- [x] Did you use Material-UI wherever possible?
- [x] Did you format according to Prettier?
- [x] Did you run all of your most recent changes locally to make sure everything is working?

### CODE REVIEW

File: client/src/components/Chart.jsx [hunk 1]
```diff
@@ -60,12 +60,13 @@ const Chart = ({ chartType }) => {
...
-            dataPoint.physical.feverSeverity = 0;
-          }
 
-          if (!parseInt(dataPoint.physical.feverSeverity, 10) > 0) {
+          let temp;
+          if (
+            !dataPoint.physical.feverSeverity ||
+            dataPoint.physical.feverSeverity === '' ||
+            !parseInt(dataPoint.physical.feverSeverity, 10) > 0
+          ) {
```
Comment (acthelemann) [inline client/src/components/Chart.jsx:69]: This was to fix a lint issue.

File: client/src/components/survey/SurveyPage3.jsx [hunk 2]
```diff
@@ -40,26 +40,25 @@ const SurveyPage3 = props => {
...
 
-    userSession
-      .putFile(`observation/${fileNumber}.json`, JSON.stringify(observation), encryptOptions)
-      .then(() => {
-        history.push('/');
-      })
-      .catch(err => {
-        console.log(err);
+    try {
+      await userSession.putFile(`observation/${fileNumber}.json`, JSON.stringify(observation), encryptOptions);
```
Comment (SomeMoosery) [inline client/src/components/survey/SurveyPage3.jsx:50]: How could I have forgotten `await` 🤦‍♂

**Comment by SomeMoosery** [comment]
hat trick 🎩
