### PR TITLE
get oneThird Value based off slider width instead of screen width

### LINKED ISSUE #495: Log health slider more options needs too much sliding on large screens
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in QA
    * Followed all applicable steps in the TROUBLESHOOTING guide: TODO
    * Checked for relevant discussions on Discord: <https://discord.gg/pPERUuv>
    * Checked that your issue isn't already filed: <https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues>

### Description

The log health slider needs to be moved too much to show more options on large screens.

### Steps to Reproduce

1. Use a screen size >= 839px
2. Go to Calendar page
3. Drag slider just past the vertical bar
4. See that the slider doesn't stay past the vertical bar

**Expected behavior:**

Slider stays past the vertical bar when dragging it just past the vertical bar.

**Actual behavior:**

Slider returns back to its original position when dragging it just past the vertical bar.

**Reproduces how often:**

100%

### Versions

0.3.24

### Additional Information

log-health-slider-bug

### PR DESCRIPTION
**Pull request by PhurbaSherpa**
## IMPORTANT: Please do not create a Pull Request without creating an issue first.

**Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request.**

**Do not change the following line aside from replacing YOUR-ISSUE-HERE with the issue this PR fixes** 

fixes #495 

### Please provide enough information so that others can review your pull request:
1. Go to Calendar Page in screen sizes
-  screen size >= 839px 
-  screen size < 839px
2. Drag slider just past vertical line
3. See that the slider stays at the line

### Explain the **details** for making this change. What existing problem does the pull request solve?

The slider placement was being calculated based off the screen width and since the slider has a different view width for bigger views I decided to calculate the sliders placement based off the sliders width instead. Now when you go past the vertical line the slider stops at the vertical line.

### Test plan (required)
slider

Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

### Final Checklist

- [ ] Have you bumped the version in `package.json`?
    - Second decimal for major change, third decimal for minor change. This can go past 10 i.e. 1.0.9 !=> 1.1.0, 1.0.9 => 1.0.10
    - [Read here for more info](https://semver.org/)
- [x] Have you added any new tests necessary?
- [x] Is your PR rebased off the most current master?
- [x] Have you squashed all commits, or if you will merge will you squash all commits?
- [x] Did you use yarn, not npm?
- [x] Did you use Material-UI wherever possible?
- [x] Did you format according to Prettier?
- [x] Did you run all of your most recent changes locally to make sure everything is working?

### CODE REVIEW

File: client/src/components/LogHealthSlider.jsx [hunk 1]
```diff
@@ -83,7 +83,19 @@ const useStyles = makeStyles(theme => ({
 const LogHealthSlider = () => {
   const classes = useStyles();
   const history = useHistory();
-  const oneThird = window.innerWidth / 3; // Note: doesn't support window resizing
+  const [oneThird, setOneThird] = useState(0);
+
+  useEffect(() => {
+    // grab slider element and use its width to calculate the oneThird Value
+    let slider = document.querySelector('.makeStyles-item-250');
```
Comment (SomeMoosery) [inline client/src/components/LogHealthSlider.jsx:90]: instead of using an auto-generated class here, we should go in and give whichever item you're selecting a class ourselves

File: client/src/components/LogHealthSlider.jsx [hunk 2]
```diff
@@ -83,7 +83,19 @@ const useStyles = makeStyles(theme => ({
...
+    getSliderBound();
+    function getSliderBound() {
+      let newOneThird = slider.clientWidth / 3;
```
Comment (SomeMoosery) [inline client/src/components/LogHealthSlider.jsx:93]: I think this can be a `const`

Comment (PhurbaSherpa) [reply client/src/components/LogHealthSlider.jsx]: just fixed the changes

**Comment by SomeMoosery** [comment]
Looks like tests are failing due to snapshot, try running `yarn run test -u` to update the snapshot
